Apotek/Controllers/JenisController.cs
using Apotek.Models;
using Microsoft.AspNetCore.Mvc;

namespace Apotek.Controllers
{
    public class JenisController : Controller
    {
        private static List<Models.Jenis> jeniss = InitializeData();

        private static List<Models.Jenis> InitializeData()
        {
            List<Models.Jenis> initialData = new List<Models.Jenis>
            {
                new Models.Jenis
                {
                    idJenis = 1,
                    namaJenis = "Batuk",
                    
                },
                new Models.Jenis
                {
                    idJenis = 2,
                    namaJenis = "Pilek",
                   
                }
            };
            return initialData;
        }
        public IActionResult Index()
        {
            List<Models.Jenis> jenisList = jeniss.ToList();
            return View(jenisList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Models.Jenis jenis)
        {
            if (ModelState.IsValid)
            {
                int new_id = 1;

                while (jeniss.Any(b => b.idJenis == new_id))
                {
                    new_id++;
                }

                jenis.idJenis= new_id;

                jeniss.Add(jenis);
                TempData["SuccessMessage"] = "Data berhasil ditambahkan";
                return RedirectToAction("Index");
            }

            return View(jenis);
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var response = new { success = false, message = "Gagal menghapus Jenis." };
            int idpass = id;
            try
            {
                var jenis = jeniss.FirstOrDefault(b => b.idJenis == id);
                if (jenis != null)
                {
                    jeniss.Remove(jenis);
                    response = new { success = true, message = "Jenis berhasil dihapus." };
                }
                else
                {
                    response = new { success = false, message = "Jenis tidak ditemukan." };
                }
            }
            catch (Exception ex)
            {
                response = new { success = false, message = ex.Message };
            }

            return Json(response);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Models.Jenis jenis = jeniss.FirstOrDefault(b => b.idJenis == id);

            if (jenis == null)
            {
                return NotFound();
            }

            return View(jenis);
        }

        [HttpPost]
        public IActionResult Edit(Models.Jenis jenis)
        {
            if (ModelState.IsValid)
            {
                Models.Jenis newJenis = jeniss.FirstOrDefault(b => b.idJenis == jenis.idJenis);

                if (newJenis == null)
                {
                    return NotFound();
                }

                newJenis.namaJenis = jenis.namaJenis;

                TempData["SuccessMessage"] = "Jenis berhasil diupdate.";
                return RedirectToAction("Index");
            }

            return View(jenis);
        }
    }
}

Apotek/Controllers/ObatController.cs
using Apotek.Models;
using Microsoft.AspNetCore.Mvc;

namespace Apotek.Controllers
{
    public class ObatController : Controller
    {
        private static List<Models.Obat> obats = InitializeData();

        private static List<Models.Obat> InitializeData()
        {
            List<Models.Obat> initialData = new List<Models.Obat>
            {
                new Models.Obat
                {
                    idObat = "OBA001",
                    idJenis = 1,
                    namaObat = "Paracetamol",
                    tanggalKadaluarsaObat = new DateTime(2025, 1, 2),
                    hargaObat = 50000,

                },
                new Models.Obat
                {
                    idObat = "OBA002",
                    idJenis = 2,
                    namaObat = "Kombatrin",
                    tanggalKadaluarsaObat = new DateTime(2024, 4, 2),
                    hargaObat = 40000,

                }
            };
            return initialData;
        }
        public IActionResult Index()
        {
            List<Models.Obat> obatList = obats.ToList();
            return View(obatList);
           
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Models.Obat obat)
        {
            if (ModelState.IsValid)
            {
                
                obats.Add(obat);
                TempData["SuccessMessage"] = "Data berhasil ditambahkan";
                return RedirectToAction("Index");
            }

            return View(obat);
        }
        [HttpPost]
        public IActionResult Delete(string id)
        {
            var response = new { success = false, message = "Gagal menghapus Obat." };
            string idpass = id;
            try
            {
                var obat = obats.FirstOrDefault(b => b.idObat == id);
                if (obat != null)
                {
                    obats.Remove(obat);
                    response = new { success = true, message = "Obat berhasil dihapus." };
                }
                else
                {
                    response = new { success = false, message = "Obat tidak ditemukan." };
                }
            }
            catch (Exception ex)
            {
                response = new { success = false, message = ex.Message };
            }

            return Json(response);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            Models.Obat obat = obats.FirstOrDefault(b => b.idObat == id);

            if (obat == null)
            {
                return NotFound();
            }

            return View(obat);
        }

        [HttpPost]
        public IActionResult Edit(Models.Obat obat)
        {
            if (ModelState.IsValid)
            {
                Models.Obat newObat = obats.FirstOrDefault(b => b.idObat == obat.idObat);

                if (newObat == null)
                {
                    return NotFound();
                }

                newObat.idJenis = obat.idJenis;
                newObat.namaObat = obat.namaObat;
                newObat.tanggalKadaluarsaObat = obat.tanggalKadaluarsaObat;
                newObat.hargaObat = obat.hargaObat;

                TempData["SuccessMessage"] = "Obat berhasil diupdate.";
                return RedirectToAction("Index");
            }

            return View(obat);
        }
    }
}

Apotek/Controllers/PembelianController.cs
using Apotek.Models;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.PortableExecutable;

namespace Apotek.Controllers
{
    public class PembelianController : Controller
    {
        private static List<Models.Pembelian> pembelians = InitializeData();

        private static List<Models.Pembelian> InitializeData()
        {
            List<Models.Pembelian> initialData = new List<Models.Pembelian>
            {
                new Models.Pembelian
                {
                    idTransaksi = "TRS001",
                    tanggalTransaksi = new DateTime(2023,12,12),
                    idObat = "OBA001",
                    jumlah = 2,
                    totalHarga = 25000,


                },
                new Models.Pembelian
                {
                    idTransaksi = "TRS002",
                    tanggalTransaksi = new DateTime(2023,5,12),
                    idObat = "OBA002",
                    jumlah = 1,
                    totalHarga = 10000,

                }
            };
            return initialData;
        }
        public IActionResult Index()
        {
            List<Models.Pembelian> pembelianList = pembelians.ToList();
            return View(pembelianList);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Pembelian pembelian)
        {
            if (ModelState.IsValid)
            {

                pembelian.totalHarga = pembelian.jumlah * 5000;
                pembelians.Add(pembelian);
                TempData["SuccessMessage"] = "Data berhasil ditambahkan";
                return RedirectToAction("Index");
            }

            return View(pembelian);
        }
    }
}

Apotek/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]- Apotek</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Apotek.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Apotek</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Apotek - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Apotek/Views/Shared/_LayoutAdmin.cshtml
<!--
=========================================================
* Argon Dashboard 2 - v2.0.4
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/favicon.png">
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">
    <title>
        Apotek
    </title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <!-- Nucleo Icons -->
    <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- CSS Files -->
    <link id="pagestyle" href="~/assets/css/argon-dashboard.css?v=2.0.4" rel="stylesheet" />
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    <aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <a class="navbar-brand m-0">
                <img src="./assets/img/logo-ct-dark.png" class="navbar-brand-img h-100" alt="main_logo">
                <span class="ms-1 font-weight-bold">Apotek</span>
            </a>
        </div>
        <hr class="horizontal dark mt-0">
        <div class="navbar-collapse  w-auto " id="sidenav-collapse-main">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Home" asp-action="Index">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Jenis" asp-action="Index">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-tag text-warning text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Master Jenis Obat</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " asp-controller="Obat" asp-action="Index">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Master Obat</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " asp-controller="Pembelian" asp-action="Index">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-app text-info text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Pembelian Obat</span>
                    </a>
                </li>
            </ul>
        </div>
    </aside>
    <main class="main-content position-relative border-radius-lg ">
        <!-- Navbar -->
        <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
            <div class="container-fluid py-1 px-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                        <li class="breadcrumb-item text-sm"><a class="opacity-5 text-white" href="javascript:;">Pages</a></li>
                        <li class="breadcrumb-item text-sm text-white active" aria-current="page">Dashboard</li>
                    </ol>
                    <h6 class="font-weight-bolder text-white mb-0">Dashboard</h6>
                </nav>
                <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                    <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                        <div class="input-group">
                            <span class="input-group-text text-body"><i class="fas fa-search" aria-hidden="true"></i></span>
                            <input type="text" class="form-control" placeholder="Type here...">
                        </div>
                    </div>
                    <ul class="navbar-nav  justify-content-end">
                        <li class="nav-item d-flex align-items-center">
                            <a href="javascript:;" class="nav-link text-white font-weight-bold px-0">
                                <i class="fa fa-user me-sm-1"></i>
                                <span class="d-sm-inline d-none">Sign In</span>
                            </a>
                        </li>
                        <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                            <a href="javascript:;" class="nav-link text-white p-0" id="iconNavbarSidenav">
                                <div class="sidenav-toggler-inner">
                                    <i class="sidenav-toggler-line bg-white"></i>
                                    <i class="sidenav-toggler-line bg-white"></i>
                                    <i class="sidenav-toggler-line bg-white"></i>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item px-3 d-flex align-items-center">
                            <a href="javascript:;" class="nav-link text-white p-0">
                                <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
                            </a>
                        </li>
                        <li class="nav-item dropdown pe-2 d-flex align-items-center">
                            <a href="javascript:;" class="nav-link text-white p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-bell cursor-pointer"></i>
                            </a>
                            <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                                <li class="mb-2">
                                    <a class="dropdown-item border-radius-md" href="javascript:;">
                                        <div class="d-flex py-1">
                                            <div class="my-auto">
                                                <img src="./assets/img/team-2.jpg" class="avatar avatar-sm  me-3 ">
                                            </div>
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="text-sm font-weight-normal mb-1">
                                                    <span class="font-weight-bold">New message</span> from Laur
                                                </h6>
                                                <p class="text-xs text-secondary mb-0">
                                                    <i class="fa fa-clock me-1"></i>
                                                    13 minutes ago
                                                </p>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li class="mb-2">
                                    <a class="dropdown-item border-radius-md" href="javascript:;">
                                        <div class="d-flex py-1">
                                            <div class="my-auto">
                                                <img src="./assets/img/small-logos/logo-spotify.svg" class="avatar avatar-sm bg-gradient-dark  me-3 ">
                                            </div>
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="text-sm font-weight-normal mb-1">
                                                    <span class="font-weight-bold">New album</span> by Travis Scott
                                                </h6>
                                                <p class="text-xs text-secondary mb-0">
                                                    <i class="fa fa-clock me-1"></i>
                                                    1 day
                                                </p>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        </main>
        <!-- End Navbar -->
    
        <!--   Core JS Files   -->
        <script src="~/assets/js/core/popper.min.js"></script>
        <script src="~/assets/js/core/bootstrap.min.js"></script>
        <script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
        <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
        <script src="~/assets/js/plugins/chartjs.min.js"></script>
    
        <!-- Vendor JS Files -->
        <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
        <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
        <script src="~/assets/vendor/echarts/echarts.min.js"></script>
        <script src="~/assets/vendor/quill/quill.min.js"></script>
        <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
        <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
        <script src="~/assets/vendor/php-email-form/validate.js"></script>

        <!-- Template Main JS File -->
        <script src="~/assets/js/main.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://unpkg.com/sweetalert@2.1.2/dist/sweetalert.min.js"></script>

        <script>
            var win = navigator.platform.indexOf('Win') > -1;
            if (win && document.querySelector('#sidenav-scrollbar')) {
                var options = {
                    damping: '0.5'
                }
                Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
            }
        </script>
        <!-- Github buttons -->
        <script async defer src="https://buttons.github.io/buttons.js"></script>
        <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
        <script src="~/assets/js/argon-dashboard.min.js?v=2.0.4"></script>
</body>

</html>